config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies
  get '/find_by_title/:title' => 'movies#search', as: :find_by_title
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/example.rb
class Example < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  def self.all_ratings
    %w[G PG PG-13 R]
  end

  def self.find_by_title movie_title
    director = Movie.find_by(title: movie_title).director
    return nil if director.blank? or director.nil?
    Movie.where(director: director).pluck(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @all_ratings = Movie.all_ratings

    session[:ratings] = @ratings = params[:ratings].try(:keys) || session[:ratings] || @all_ratings
    session[:sort] = @sort = params[:sort] || session[:sort]

    if @sort != params[:sort] || @ratings != params[:ratings]
      redirect_to movies_path(sort: @sort, ratings: @ratings)
    else
      @movies = Movie.where(rating: @ratings).order(@sort)
    end
  end

  def search
    @similar_movies = Movie.find_by_title(params[:title])
    if @similar_movies.nil?
      redirect_to root_url, alert: "'#{params[:title]}' has no director information"
    end
    @movie = Movie.find_by(title: params[:title])
  end

  # GET /movies/1 or /movies/1.json
  def show
    id = params.require(:id)
    @movie = Movie.find(id)
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find params[:id]
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_movie
    @movie = Movie.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :release_date, :director)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EsasS12021Assign2</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="ui top fixed menu">
  <div class="item">
    <h3><%=link_to 'Rotten Potatoes', movies_path %></h3>
  </div>
</div>
<div class="ui container main">
  <%= yield %>
</div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, html: { class: "ui form" }) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= select :movie, :rating, ['G','PG','PG-13','R'] %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field inline">
    <%= form.label :release_date %>
    <br/>
    <%= form.date_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="actions">
    <%= form.submit class: "ui primary button" %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1 class="ui header">
  Editing Movie
</h1>

<%= render 'form', movie: @movie %>
<%= form_tag movie_path(@movie), :method => :put do %>
<%= label :movie, :director, 'Director', :class => 'col-form-label' %>

<div class="ui basic buttons">
  <%= link_to movies_path, class: "ui button" do %>
    <i class="chevron left icon"></i> Back
  <% end %>
  <%= link_to @movie, class: "ui button" do %>
    <i class="eye"></i> Show
  <% end %>
</div>

<% end %>

app/views/movies/index.html.erb
<h1 class="ui header">
  Movies
  <%= link_to new_movie_path, class: "ui primary right floated button" do %>
    <i class="add icon"></i> New Movie
  <% end %>
</h1>

<%= semantic_flash %>

<%= form_tag movies_path, method: :get do %>
  <div class="ui form">
    <div class="inline fields">
      <label>Include:</label>
      <% @all_ratings.each do |rating| %>
        <div class="field">
          <div class="ui checkbox">
            <%= check_box_tag "ratings[#{rating}]", true, @ratings.include?(rating) %>
            <label><%= rating %></label>
          </div>
        </div>
      <% end %>
      <%= submit_tag 'Refresh', class: "ui tiny green button" %>
    </div>
  </div>
<% end %>

<table class="ui table">
  <thead>
  <tr>
    <th>
      <%= link_to movies_path(sort: "title") do %>
        Title
        <% if @sort == "title" %>
          <i class="chevron up icon"></i>
        <% end %>
      <% end %>
    </th>
    <th>Rating</th>
    <th>Description</th>
    <th>
      <%= link_to movies_path(sort: "release_date") do %>
        Release Date
        <% if @sort == "release_date" %>
          <i class="chevron up icon"></i>
        <% end %>
      <% end %>
    </th>
    <th class="right aligned"></th>
  </tr>
  </thead>

  <tbody>
  <% @movies.each do |movie| %>
    <tr>
      <td><%= movie.title %></td>
      <td><%= movie.rating %></td>
      <td><%= movie.description %></td>
      <td><%= movie.release_date %></td>
      <td class="right aligned">
        <div class="ui small basic buttons">
          <%= link_to movie, class: "ui button" do %>
            <i class="eye icon"></i> Show
          <% end %>
          <%= link_to edit_movie_path(movie), class: "ui button" do %>
            <i class="edit icon"></i> Edit
          <% end %>
          <%= link_to movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui button" do %>
            <i class="remove icon"></i> Destroy
          <% end %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/movies/new.html.erb
<h1 class="ui header">
  New Movie
</h1>

<%= render 'form', movie: @movie %>

<%= link_to movies_path, class: "ui basic button" do %>
  <i class="chevron left icon"></i> Back
<% end %>

app/views/movies/search.html.erb
<h1 class="ui header">
  Similar Movies for
  <%= @movie.title.blank? ? "Movie" : @movie.title %>
</h1>

<ul>
  <% @similar_movies.each do |movie_title| %>
      <li>
        <%= movie_title %>
      </li>
    <% end %>
</ul>

<div class="ui basic buttons">
  <%= link_to movies_path, class: "ui button" do %>
    <i class="chevron left icon"></i> Back
  <% end %>
</div>

app/views/movies/show.html.erb
<h1 class="ui header">
  <%= @movie.title.blank? ? "Movie" : @movie.title %>
</h1>

<%= semantic_flash %>

<div class="ui card">
  <div class="content">
    <div class="ui divided very relaxed list">
      <div class="item">
        <div class="header">
          Rating
        </div>
        <%= @movie.rating %>
      </div>
      <div class="item">
        <div class="header">
          Description
        </div>
        <%= @movie.description %>
      </div>

      <div class="item">
        <div class="header">
          Release date
        </div>
        <%= @movie.release_date %>
      </div>
      <div class="item">
        <div class="header">
          Director
        </div>
        <%= @movie.director %>
      </div>
    </div>
  </div>
</div>

<div class="ui basic buttons">
  <%= link_to movies_path, class: "ui button" do %>
    <i class="chevron left icon"></i> Back
  <% end %>
  <%= link_to edit_movie_path(@movie), class: "ui button" do %>
    <i class="edit"></i> Edit
  <% end %>
  <%= link_to find_by_title_path(@movie.title), class: "ui button" do %>
    <i> </i> Find Same Director
  <% end %>
</div>